<?php

/*
 * @file
 * This file demonstrates how to use hook functions
 */

/*
 * Implements hook_cron()
 */
function scp_foundation_cron() {
  \Drupal::messenger()->addMessage(t("Hello from scp_foundation cron hook"));
}

/*
 * Implements hook_form_alter()
 */
function scp_foundation_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
	\Drupal::messenger()->addMessage(t("Form id is: @id", ["@id" => $form_id]));
  if($form_id == 'node_article_edit_form'){
    $form['actions']['submit']['#value'] = t("Save this [redacted] article");
  }
}
